server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service # 路由id，自定义，唯一即可
#          uri: http://127.0.0.1:8081 # 路由的目标地址，这样配是固定地址
          uri: lb://UserService # 路由的目标地址，lb是负载均衡的缩写，后面跟服务名
          predicates: # 路由断言，判断请求是否符合路由的规则条件
            - Path=/user/** # 按访问路径匹配，符合条件的才会路由
        - id: order-serive
          uri: lb://OrderService
          predicates:
            - Path=/order/**